apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: dockercoins
    app: hasher
  name: hasher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: dockercoins
        app: hasher
    spec:
      containers:
      - image: chrch/hasher:1.0
        name: hasher