apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: {{.Release.Name}}
    app: hasher
  name: hasher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: {{.Release.Name}}
        app: hasher
    spec:
      containers:
      - image: chrch/hasher:1.0
        name: hasher