apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hasher
  name: hasher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - image: chrch/hasher
        name: hasher