apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: dockercoins
    app: redis
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: dockercoins
        app: redis
    spec:
      containers:
      - image: redis:4.0.6
        name: redis