apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - image: chrch/rng
        name: rng