apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: dockercoins
    app: rng
  name: rng
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: dockercoins
        app: rng
    spec:
      containers:
      - image: chrch/rng:1.0
        name: rng