apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: {{ .Release.Name }}
    app: rng
  name: {{ .Release.Name }}-rng
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: {{ .Release.Name }}
        app: rng
    spec:
      containers:
      - image: chrch/rng:1.0
        name: {{ .Release.Name }}-rng