apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: {{.Release.Name}}
    app: webui
  name: {{ .Release.Name }}-webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: {{.Release.Name}}
        app: webui
    spec:
      containers:
      - image: chrch/webui:1.0
        name: {{ .Release.Name }}-webui