apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: dockercoins
    app: webui
  name: webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        stack: dockercoins
        app: webui
    spec:
      containers:
      - image: chrch/webui:1.0
        name: webui