apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: chrch/worker:{{ .Values.worker.imageTag }}
        name: worker      
      
