apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: worker
  name: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: worker
    spec:
      containers:
      - image: chrch/worker
        name: worker