apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    stack: {{.Release.Name}}
    app: worker
  name: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  template:
    metadata:
      labels:
        stack: {{.Release.Name}}
        app: worker
    spec:
      containers:
      - image: chrch/worker:1.0
        name: worker      
      